import jsPDF from "jspdf";

interface FactCheckData {
  content: string;
  verdict?: string;
  trustScore?: number;
  summary?: string;
  explanation?: string;
  references: Array<{
    type: string;
    title: string;
    authors?: string;
    publisher?: string;
    publicationDate?: string;
  }>;
  createdAt: Date;
}

const verdictLabels: Record<string, string> = {
  CONFIRMED: "사실로 확인됨",
  MOSTLY_TRUE: "대체로 사실",
  CAUTION: "주의 필요",
  FALSE: "거짓",
  UNVERIFIABLE: "검증 불가",
};

export function generateFactCheckPDF(data: FactCheckData) {
  const doc = new jsPDF();

  let yPosition = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FactChecker Report", margin, yPosition);
  yPosition += 15;

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date(data.createdAt).toLocaleDateString("ko-KR")}`,
    margin,
    yPosition
  );
  yPosition += 15;

  // Content
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Checked Content:", margin, yPosition);
  yPosition += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const contentLines = doc.splitTextToSize(data.content, maxWidth);
  doc.text(contentLines, margin, yPosition);
  yPosition += contentLines.length * 5 + 10;

  // Verdict and Trust Score
  if (data.verdict) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const verdictText = `Verdict: ${verdictLabels[data.verdict] || data.verdict}`;
    doc.text(verdictText, margin, yPosition);
    yPosition += 10;

    if (data.trustScore !== undefined && data.trustScore !== null) {
      doc.setFontSize(12);
      doc.text(`Trust Score: ${data.trustScore.toFixed(0)}/100`, margin, yPosition);
      yPosition += 15;
    }
  }

  // Summary
  if (data.summary) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Summary:", margin, yPosition);
    yPosition += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(data.summary, maxWidth);
    doc.text(summaryLines, margin, yPosition);
    yPosition += summaryLines.length * 5 + 10;
  }

  // Explanation
  if (data.explanation) {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Detailed Analysis:", margin, yPosition);
    yPosition += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const explanationLines = doc.splitTextToSize(data.explanation, maxWidth);

    // Split explanation across pages if needed
    for (let i = 0; i < explanationLines.length; i++) {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(explanationLines[i], margin, yPosition);
      yPosition += 5;
    }
    yPosition += 10;
  }

  // References
  if (data.references.length > 0) {
    // Check if we need a new page
    if (yPosition > 240) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("References:", margin, yPosition);
    yPosition += 10;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    data.references.forEach((ref, index) => {
      // Check if we need a new page
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }

      const refText = `${index + 1}. ${ref.title}`;
      const refLines = doc.splitTextToSize(refText, maxWidth - 10);
      doc.text(refLines, margin + 5, yPosition);
      yPosition += refLines.length * 4;

      if (ref.authors) {
        doc.setFont("helvetica", "italic");
        const authorsText = `   Authors: ${ref.authors}`;
        doc.text(authorsText, margin + 5, yPosition);
        yPosition += 4;
        doc.setFont("helvetica", "normal");
      }

      if (ref.publisher) {
        const publisherText = `   Publisher: ${ref.publisher}`;
        doc.text(publisherText, margin + 5, yPosition);
        yPosition += 4;
      }

      if (ref.publicationDate) {
        const dateText = `   Date: ${ref.publicationDate}`;
        doc.text(dateText, margin + 5, yPosition);
        yPosition += 4;
      }

      yPosition += 3; // Space between references
    });
  }

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  doc.setPage(pageCount);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Generated by FactChecker - AI-powered fact-checking service",
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  // Save the PDF
  const fileName = `factcheck-${new Date().getTime()}.pdf`;
  doc.save(fileName);
}
